# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: Dr. Randal S. Olson
# Description of the Site
description: Full stack data scientist and artificial intelligence researcher
# URL of Image of the Site
site-image: /assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: /assets/images/favicon.ico

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: randal.s.olson@gmail.com
facebook_username: RandalSOlson
twitter_username: randal_olson
instagram_username: randal.s.olson
linkedin_username: randalolson
github_username:  rhiever
youtube_channel_id: UCvEj2pLBlh_LpfJx7LxXh9A
reddit_username:
behance_username:
dribbble_username:
spotify_username:

# Google Analytics
google-analytics: UA-3573562-2

# Disqus
disqus-shortname:

# Name of the Author
author-name: Dr. Randal S. Olson
# URL for the Image of the Author
author-image: /assets/images/randal-olson.jpg
# 60 Words About the Author
author-about: "Hi! I'm <strong>Dr. Randal S. Olson</strong>. I'm a full stack data scientist and AI researcher based in the Portland, Oregon metropolitan area.<br /><br />

I specialize in artificial intelligence, machine learning, data science, and data visualization, and occasionally write about my latest work on my <a href='blog/'>personal blog</a>, where I've become known for computing optimal road trips around the world and solving <em>Where’s Waldo?</em>, among many other creative applications of machine learning. My work has been featured all over the world and in the news, including the <a href='https://www.nytimes.com/2015/03/14/upshot/stuff-we-liked.html'>New York Times</a>, <a href='https://www.wired.com/2015/02/created-perfect-wheres-waldo-strategy-machine-learning/'>Wired</a>, <a href='https://fivethirtyeight.com/features/what-12-months-of-record-setting-temperatures-looks-like-across-the-u-s/'>FiveThirtyEight</a>, <a href='https://www.theonion.com/study-settling-for-adequate-partner-better-than-waitin-1819562531'>The Onion</a>, and much more.<br /><br />

I work tirelessly to promote open and reproducible science, leading by example and openly publishing my work on <a href='https://github.com/rhiever/Data-Analysis-and-Machine-Learning-Projects'>GitHub</a> and <a href='https://scholar.google.com/citations?user=LU96GEAAAAAJ&hl=en'>open access journals</a> whenever I can. I'm also passionate about training the next generation of data scientists to be more efficient, effective, and collaborative in their work, and do so by <a href='https://nbviewer.org/github/rhiever/Data-Analysis-and-Machine-Learning-Projects/blob/master/example-data-science-notebook/Example%20Machine%20Learning%20Notebook.ipynb'>writing online tutorials</a>, <a href='http://shop.oreilly.com/product/0636920046592.do'>recording video tutorials</a>, <a href='https://software-carpentry.org/'>teaching hands-on workshops</a>, and <a href='mentoring/'>mentoring local students</a> in my research specialties.<br /><br />

If you'd like to talk data, ask about one of my projects, hire me to consult on a project, or anything else, feel free to contact me directly at the link below."
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: http://www.randalolson.com/

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Excludes
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
